name: pull request

on:
  pull_request:
    paths:
      - 'source/DefaultDocumentation/**'

jobs:
  pull_request:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301

    - name: Compile
      run: dotnet build source\DefaultDocumentation\DefaultDocumentation.csproj -c Release